const fs = require('fs');
const path = require('path');

const envFile = path.join(__dirname, '../src/environments/environment.ts');

const apiUrl = process.env.API_URL || 'http://localhost:3100/api/v1';
const production = process.env.PRODUCTION === 'true';

const content = `// Auto-generated by set-env.js - DO NOT EDIT MANUALLY
export const environment = {
  production: ${production},
  apiUrl: '${apiUrl}',
};
`;

fs.writeFileSync(envFile, content);
console.log(`Environment file generated: ${envFile}`);
console.log(`  production: ${production}`);
console.log(`  apiUrl: ${apiUrl}`);
