const fs = require('fs');
const path = require('path');
const dotenv = require('dotenv');

// Get environment from command line argument or default to 'local'
const env = process.argv[2] || 'local';
const envFilePath = path.join(__dirname, `../.env.${env}`);

// Check if .env file exists
if (!fs.existsSync(envFilePath)) {
  console.error(`ERROR: Environment file not found: ${envFilePath}`);
  process.exit(1);
}

// Load .env file
const envConfig = dotenv.parse(fs.readFileSync(envFilePath));

const apiUrl = envConfig.API_URL || 'http://localhost:3100/api/v1';
const production = envConfig.PRODUCTION === 'true';

// Generate environment.ts
const targetPath = path.join(__dirname, '../src/environments/environment.ts');
const content = `// Auto-generated by set-env.js from .env.${env} - DO NOT EDIT MANUALLY
export const environment = {
  production: ${production},
  apiUrl: '${apiUrl}'
};
`;

fs.writeFileSync(targetPath, content);
console.log(`✓ Environment file generated: ${targetPath}`);
console.log(`  Source: .env.${env}`);
console.log(`  production: ${production}`);
console.log(`  apiUrl: ${apiUrl}`);
