const fs = require('fs');
const path = require('path');
const dotenv = require('dotenv');

// Get environment from command line argument or default to 'local'
const env = process.argv[2] || 'local';
const envFilePath = path.join(__dirname, `../.env.${env}`);

let envConfig;

// Check if .env file exists (local development)
if (fs.existsSync(envFilePath)) {
  // Load .env file
  envConfig = dotenv.parse(fs.readFileSync(envFilePath));
  console.log(`✓ Loaded environment from: .env.${env}`);
} else {
  // If .env file doesn't exist (e.g., Docker/Coolify), use process.env
  console.log(`⚠ .env.${env} not found, using environment variables`);
  envConfig = process.env;
}

const apiUrl = envConfig.API_URL || 'http://localhost:3100/api/v1';
const production = envConfig.PRODUCTION === 'true';

// Generate environment.ts
const targetPath = path.join(__dirname, '../src/environments/environment.ts');
const envDir = path.dirname(targetPath);

// Create directory if it doesn't exist
if (!fs.existsSync(envDir)) {
  fs.mkdirSync(envDir, { recursive: true });
}

const content = `// Auto-generated by set-env.js from ${fs.existsSync(envFilePath) ? '.env.' + env : 'environment variables'} - DO NOT EDIT MANUALLY
export const environment = {
  production: ${production},
  apiUrl: '${apiUrl}'
};
`;

fs.writeFileSync(targetPath, content);
console.log(`✓ Environment file generated: ${targetPath}`);
console.log(`  production: ${production}`);
console.log(`  apiUrl: ${apiUrl}`);
